hezhijie0327/lobe-chat

src/app/(main)/settings/system-agent/features/Topic.tsx, src/app/(main)/settings/system-agent/features/Translation.tsx
=> 💄 style: update coding style

src/app/(main)/settings/system-agent/features/AgentMeta.tsx, src/app/(main)/settings/system-agent/features/Topic.tsx, src/app/(main)/settings/system-agent/features/Translation.tsx
=> 🔨 chore: removed 'form' from trigger

src/libs/agent-runtime/baichuan/index.ts
=> Frequency penalty

src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
=> 💄 style: update ProviderAvatar for Baichuan & Stepfun

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/app/api/chat/agentRuntime.ts, src/components/ModelIcon/index.tsx, src/components/ModelProviderIcon/index.tsx, src/config/llm.ts, src/config/modelProviders/index.ts, src/config/modelProviders/taichu.ts, src/const/settings/llm.ts, src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx, src/libs/agent-runtime/AgentRuntime.ts, src/libs/agent-runtime/taichu/index.test.ts, src/libs/agent-runtime/taichu/index.ts, src/libs/agent-runtime/types/type.ts, src/server/globalConfig/index.ts, src/types/user/settings/keyVaults.ts
=> ✨ feat: Add Taichu model provider

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/app/api/chat/agentRuntime.ts, src/components/ModelIcon/index.tsx, src/components/ModelProviderIcon/index.tsx, src/config/llm.ts, src/config/modelProviders/index.ts, src/config/modelProviders/zhinao.ts, src/const/settings/llm.ts, src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx, src/libs/agent-runtime/AgentRuntime.ts, src/libs/agent-runtime/types/type.ts, src/libs/agent-runtime/zhinao/index.test.ts, src/libs/agent-runtime/zhinao/index.ts, src/server/globalConfig/index.ts, src/types/user/settings/keyVaults.ts
=> ✨ feat: Add Zhinao model provider

src/libs/agent-runtime/spark/index.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
=> 🐛 fix: fixed "'$.header.uid' length must be less or equal than 32" with Spark Lite

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/components/ModelIcon/index.tsx, src/components/ModelProviderIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
=> 💄 style: update Ai360 icon

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx
=> 💄 style: resize Taichu icon

src/libs/agent-runtime/spark/index.test.ts, src/libs/agent-runtime/spark/index.ts
=> 🔨 chore: disable stream mode

src/libs/agent-runtime/spark/index.test.ts, src/libs/agent-runtime/spark/index.ts
Reverts hezhijie0327/lobe-chat#24
=> Revert "🔨 chore: disable stream mode"

src/components/ModelIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/config/modelProviders/zhipu.ts
=> 💄 style: update Zhipu models (GLM & CodeGeeX)

src/components/ModelIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/config/modelProviders/zhipu.ts
=> 💄 style: update Zhipu models (GLM & CodeGeeX) (#31)

src/components/ModelIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx
=> 💄 style: update CodeGeeX icon

src/components/ModelIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/config/modelProviders/spark.ts
=> 💄 style: add Spark Pro-128K new model

src/features/Conversation/Error/APIKeyForm/Spark.tsx, src/features/Conversation/Error/APIKeyForm/index.tsx
=> 💄style: improve APIKeyForm for Spark

src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx, src/features/Conversation/Error/APIKeyForm/Spark.tsx, src/locales/default/modelProvider.ts
=> 💄 style: improve custom API display

src/components/ModelIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/config/modelProviders/mistral.ts
=> 💄 style: update Mistral models

src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
=> 🔨 chore: merge `noUserId`

src/components/ModelTag/ModelIcon.tsx
=> 💄 style: fix stepfun & baichuan model tag icon missing

src/components/ModelIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/config/modelProviders/ollama.ts
=> 💄 style: update ollama model info

src/components/ModelIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx
=> 💄 style: update Aya icon

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/app/api/chat/agentRuntime.ts, src/components/ModelIcon/index.tsx, src/components/ModelProviderIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/config/llm.ts, src/config/modelProviders/fireworksai.ts, src/config/modelProviders/index.ts, src/const/settings/llm.ts, src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx, src/libs/agent-runtime/AgentRuntime.ts, src/libs/agent-runtime/fireworksai/index.test.ts, src/libs/agent-runtime/fireworksai/index.ts, src/libs/agent-runtime/types/type.ts, src/server/globalConfig/index.ts, src/types/user/settings/keyVaults.ts
=> Fireworksai

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/components/ModelIcon/index.tsx, src/components/ModelProviderIcon/index.tsx, src/components/ModelTag/ModelIcon.tsx, src/config/modelProviders/fireworksai.ts, src/libs/agent-runtime/fireworksai/index.test.ts
=> 💄 style: add FireworksAI self-models

src/config/modelProviders/fireworksai.ts, src/libs/agent-runtime/fireworksai/index.test.ts, src/libs/agent-runtime/fireworksai/index.ts
=> 🐛 fix: support function call

Dockerfile, Dockerfile.database, src/config/llm.ts, src/server/globalConfig/index.ts
=> ✨ feat: add `SILICONCLOUD_MODEL_LIST` support for SiliconCloud

Dockerfile, Dockerfile.database, src/config/llm.ts, src/server/globalConfig/index.ts
=> ✨ feat: add SILICONCLOUD_MODEL_LIST support for SiliconCloud

Dockerfile, Dockerfile.database, src/app/api/chat/agentRuntime.ts, src/config/llm.ts
=> ✨ feat: add baseURL support

docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.mdx, docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust.zh-CN.mdx, docs/self-hosting/environment-variables/auth.mdx, docs/self-hosting/environment-variables/auth.zh-CN.mdx
=> 📝 docs: add doc for Cloudflare Zero Trust

docs/self-hosting/environment-variables/auth.mdx, docs/self-hosting/environment-variables/auth.zh-CN.mdx
=> 📝 docs: add Generic OIDC env doc

Dockerfile, Dockerfile.database, src/app/api/chat/agentRuntime.ts, src/config/llm.ts, src/config/modelProviders/upstage.ts
=> 🔨 chore: remove proxyUrl for Upstage

Dockerfile, Dockerfile.database, src/config/llm.ts, src/server/globalConfig/index.ts
=> 💄 style: add `*_MODEL_LIST` for Qwen and ZeroOne

Dockerfile, Dockerfile.database, src/config/llm.ts, src/config/modelProviders/novita.ts, src/server/globalConfig/index.ts
=> 💄 style: update Novita AI model info & add `NOVITA_MODEL_LIST` support

Dockerfile, Dockerfile.database, src/config/llm.ts, src/config/modelProviders/groq.ts, src/server/globalConfig/index.ts
=> 💄 style: update Groq model list & add `GROQ_MODEL_LIST` support

Dockerfile, Dockerfile.database, src/app/(main)/settings/llm/ProviderList/providers.tsx, src/app/api/chat/agentRuntime.ts, src/config/llm.ts, src/config/modelProviders/ai21.ts, src/config/modelProviders/index.ts, src/const/settings/llm.ts, src/features/Conversation/Error/APIKeyForm/ProviderAvatar.tsx, src/libs/agent-runtime/AgentRuntime.ts, src/libs/agent-runtime/ai21/index.test.ts, src/libs/agent-runtime/ai21/index.ts, src/libs/agent-runtime/types/type.ts, src/server/globalConfig/index.ts, src/types/user/settings/keyVaults.ts
=> ✨ feat: add Ai21Labs model provider

src/config/modelProviders/groq.ts
=> 💄 style: add `LLaVA 1.5 7B` model in Groq

src/config/modelProviders/bedrock.ts, src/libs/agent-runtime/bedrock/index.ts, src/libs/agent-runtime/utils/streams/bedrock/ai21.ts, src/libs/agent-runtime/utils/streams/bedrock/index.ts
=> ✨ feat: support Ai21Labs model in Bedrock

src/libs/agent-runtime/utils/streams/bedrock/mistral.ts
=> 🔨 chore: support tool call for Mistral model

src/libs/agent-runtime/utils/streams/bedrock/mistral.ts
=> 🔨 chore: update stream logic

Dockerfile, Dockerfile.database
=> 🐛 fix: DNS resolving issue in Docker Compose

Dockerfile, Dockerfile.database
=> 👷 build: re-generate `resolv.conf` before running

Dockerfile, Dockerfile.database
=> 🔨 chore: add ref link to comments

src/libs/agent-runtime/utils/streams/bedrock/mistral.test.ts
=> 🔨 chore: add unit test

Dockerfile, Dockerfile.database
=> 🐛 fix: `/etc/resolv.conf`edit permission

src/libs/agent-runtime/utils/streams/openai.test.ts, src/libs/agent-runtime/utils/streams/openai.ts
=> 🐛 fix: fix CI error

Dockerfile, Dockerfile.database
=> 👷 build: change image from `musl` to `glibc`

.github/workflows/docker-base.yml, Dockerfile, Dockerfile.base, Dockerfile.database
=> 👷 build: add `lobe-chat-base` image

Dockerfile, Dockerfile.base, Dockerfile.database
=> 🐛 fix: fix file permission

Dockerfile, Dockerfile.database
=> 🐛 fix: fix `proxychains` not found conf file

Dockerfile, Dockerfile.base, Dockerfile.database
=> 🔨 chore: change default conf path of `proxychains`, limit access

Dockerfile, Dockerfile.database, scripts/serverLauncher/startServer.js
=> 👷 build: add `startServer.js` script, replace shell

src/libs/agent-runtime/utils/streams/openai.test.ts, src/libs/agent-runtime/utils/streams/openai.ts
=> 🐛 fix: fix a corner case of `tools_call` with empty object

Dockerfile, Dockerfile.database
=> 👷 build: add GitHub ENV

Dockerfile, Dockerfile.database
=> 👷 build: cleanup apt cache

Dockerfile, Dockerfile.database
=> 👷 build: fix build error

Dockerfile, Dockerfile.database
=> 👷 build: add `NODE_TLS_REJECT_UNAUTHORIZED` to ENV

Dockerfile, Dockerfile.database
=> 👷 build: optimize image size under `glibc` env

Dockerfile, Dockerfile.database
=> 👷 build: update base image comments, more suitable for current situation

Dockerfile, Dockerfile.database, scripts/serverLauncher/startServer.js
=> 👷 build: add `startServer.js` as server launcher

scripts/serverLauncher/startServer.js
=> 👷 build: check oss & auth issuer ssl connection before running

Dockerfile, Dockerfile.database
=> 👷 build: support self-signed SSL cert, switch to system-wide CA cert

scripts/serverLauncher/startServer.js
=> 👷 build: add DNS server self-check support

src/config/modelProviders/ai360.ts, src/libs/agent-runtime/ai360/index.ts
=> 💄 style: add support function call for 360AI

src/config/modelProviders/taichu.ts
=> 💄 style: add function call for `taichu_llm`

Dockerfile, Dockerfile.database
=> 👷 build: set `ENTRYPOINT` to `/bin/node`

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/config/modelProviders/hunyuan.ts, src/config/modelProviders/index.ts
=> 💄 style: enable `hunyuan-standard-256K` as default, sort model provider list

Dockerfile, Dockerfile.database
=> 👷 build: pin node LTS version to 20

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/app/api/chat/agentRuntime.ts, src/config/llm.ts, src/config/modelProviders/index.ts, src/config/modelProviders/sensecore.ts, src/const/settings/llm.ts, src/libs/agent-runtime/AgentRuntime.ts, src/libs/agent-runtime/sensecore/index.test.ts, src/libs/agent-runtime/sensecore/index.ts, src/libs/agent-runtime/types/type.ts, src/server/globalConfig/index.ts, src/types/user/settings/keyVaults.ts
=> ✨ feat: add SenseCore (商汤) model provider

src/config/modelProviders/sensecore.ts, src/libs/agent-runtime/sensecore/index.ts
=> 💄 style: update model list, fix `frequency_penalty`, `temperature`, `top_p` value range

src/app/api/chat/agentRuntime.ts, src/config/llm.ts, src/libs/agent-runtime/sensecore/authToken.ts
=> 🔨 chore: remove `SENSECORE_API_KEY` ENV, 

src/app/api/chat/agentRuntime.ts
=> 🔨 chore: add debug logs

Dockerfile, Dockerfile.database
=> 👷 build: fix `canvas_binary_host_mirror` usage

package.json, src/app/api/chat/agentRuntime.ts, src/libs/agent-runtime/sensenova/authToken.ts
=> ✨ feat: add jwt token generator for SenseNova

src/app/api/chat/agentRuntime.ts
=> ♻️ refactor: support two different type of `API TOKEN`

scripts/serverLauncher/startServer.js
=> 👷 build: detect `DB_MIGRATION_SCRIPT_PATH`, if not exist then skip

src/libs/agent-runtime/bedrock/index.ts, src/libs/agent-runtime/utils/cohereHelpers.ts
=> 🔨 chore: split `chat_history` to `buildCohereChatHistory` function

Dockerfile, Dockerfile.database, scripts/serverLauncher/startServer.js
=> 👷 build: enhance TLS cert checking & Self-host CA usage

Dockerfile, Dockerfile.database
=> 👷 build: add Wenxin ENV

src/app/(main)/settings/llm/ProviderList/SenseNova/index.tsx, src/app/(main)/settings/llm/ProviderList/providers.tsx, src/app/api/chat/agentRuntime.ts, src/config/llm.ts, src/const/auth.ts, src/features/Conversation/Error/APIKeyForm/SenseNova.tsx, src/locales/default/modelProvider.ts, src/services/_auth.ts, src/store/user/slices/modelList/selectors/keyVaults.ts, src/store/user/slices/modelList/selectors/modelConfig.ts, src/types/user/settings/keyVaults.ts
=> 💄 style: add custom form for SenseNova

src/app/(main)/settings/llm/ProviderList/SenseNova/index.tsx, src/store/user/slices/modelList/selectors/modelConfig.ts
=> 💄 style: adjust icon size

src/app/api/chat/agentRuntime.test.ts, src/app/api/chat/sensenova/route.test.ts, src/app/api/chat/sensenova/route.ts, src/services/_auth.ts
=> 🐛 fix: try to fix loading key from ENV

Dockerfile, Dockerfile.database
=> 👷 build: set `--dns-result-order=ipv4first` as default

src/libs/agent-runtime/bedrock/index.ts, src/libs/agent-runtime/utils/cohereHelpers.ts, src/libs/agent-runtime/utils/streams/bedrock/cohere.ts
=> 🔨 chore: add tools_call logic for Cohere

src/app/(backend)/webapi/chat/sensenova/route.test.ts, src/app/(backend)/webapi/chat/sensenova/route.ts, src/libs/agent-runtime/sensenova/index.ts
Reverts hezhijie0327/lobe-chat#153
=> Revert "♻️ refactor: replace `crypto-js` to `jose`, only support ENV now (Part 1)"

src/libs/agent-runtime/sensenova/authToken.ts, src/libs/agent-runtime/sensenova/index.ts
=> 🔨 chore: remove debug code

src/config/modelProviders/togetherai.ts, src/libs/agent-runtime/togetherai/__snapshots__/index.test.ts.snap
=> 💄 style: update Together AI model list, add function call & vision

src/config/modelProviders/sensenova.ts, src/libs/agent-runtime/sensenova/index.ts
=> ♻️ refactor: SenseNova, remove message convert

src/libs/agent-runtime/error.ts, src/locales/default/error.ts
=> 🔨 chore: add error message `InvalidSenseNovaArgs`

src/store/user/slices/modelList/action.ts
=> ♻️ refactor: minor logic

src/config/modelProviders/sensenova.ts, src/libs/agent-runtime/sensenova/index.ts
=> 💄 style: remove `SenseChat-Vision` model, due to model limitation

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/config/llm.ts, src/config/modelProviders/index.ts, src/config/modelProviders/xai.ts, src/const/settings/llm.ts, src/libs/agent-runtime/AgentRuntime.ts, src/libs/agent-runtime/types/type.ts, src/libs/agent-runtime/xai/index.ts, src/server/globalConfig/index.ts, src/server/modules/AgentRuntime/index.ts, src/types/user/settings/keyVaults.ts
=> ✨ feat: add support xAI provider

src/config/modelProviders/xai.ts, src/libs/agent-runtime/xai/index.test.ts
=> 💄 style: update model info

src/server/globalConfig/index.ts, src/server/routers/edge/config/__snapshots__/index.test.ts.snap
=> ♻️ refactor: minor code for modelList generate

src/server/globalConfig/index.ts
=> 🔨 chore: minor code

src/server/globalConfig/generateLLMConfig.test.ts, src/server/globalConfig/generateLLMConfig.ts, src/server/globalConfig/index.ts
=> 🔨 chore: split function & add unit test

src/config/modelProviders/xai.ts
=> 💄 style: add desc for xAI

src/server/globalConfig/generateLLMConfig.test.ts, src/server/globalConfig/generateLLMConfig.ts
=> 🔨 chore: minor code & improve `specificConfig` injection

src/const/settings/llm.ts
=> ♻️ refactor: refactor `DEFAULT_LLM_CONFIG` generate

src/const/settings/llm.ts, src/server/globalConfig/genServerLLMConfig.test.ts, src/server/globalConfig/genServerLLMConfig.ts, src/server/globalConfig/index.ts, src/utils/genUserLLMConfig.ts
=> 🔨 chore: split `genUserLLMConfig`

src/server/globalConfig/genServerLLMConfig.test.ts, src/server/globalConfig/genServerLLMConfig.ts, src/server/globalConfig/index.ts, src/utils/genUserLLMConfig.test.ts
=> ♻️ refactor: add unit test, refactor `genServerLLMConfig`

src/config/llm.ts, src/server/globalConfig/genServerLLMConfig.ts
=> ♻️ refactor: get `*_MODEL_LIST` from env

src/server/globalConfig/genServerLLMConfig.test.ts
=> 🔨 chore: udpate CI for testing `*_MODEL_LIST` from env

src/app/(main)/settings/llm/ProviderList/providers.tsx, src/config/llm.ts, src/config/modelProviders/gitee.ts, src/config/modelProviders/index.ts, src/libs/agent-runtime/AgentRuntime.ts, src/libs/agent-runtime/gitee/index.test.ts, src/libs/agent-runtime/gitee/index.ts, src/libs/agent-runtime/togetherai/__snapshots__/index.test.ts.snap, src/libs/agent-runtime/types/type.ts, src/server/modules/AgentRuntime/index.ts, src/types/user/settings/keyVaults.ts
=> ✨ feat: add Gitee model provider

src/libs/agent-runtime/gitee/index.ts
=> 🐛 fix: fix `code-raccoon-v1` topP issue

src/config/modelProviders/gitee.ts, src/libs/agent-runtime/gitee/index.ts
=> 💄 style: update model list

Dockerfile, Dockerfile.database
=> 👷 build: add docker env

Dockerfile, Dockerfile.database, src/config/llm.ts, src/server/modules/AgentRuntime/index.ts
=> 🐛 fix: fix `XAI_PROXY_URL` env missing

src/app/(backend)/_deprecated/createBizOpenAI/createAzureOpenai.ts, src/app/(backend)/_deprecated/createBizOpenAI/createOpenai.ts, src/config/llm.ts, src/server/globalConfig/genServerLLMConfig.test.ts, src/server/globalConfig/index.ts, src/server/modules/AgentRuntime/index.ts
=> ♻️ refactor: refactor `*_PROXY_URL`, get var from ENV

src/app/(backend)/_deprecated/createBizOpenAI/createAzureOpenai.ts, src/config/modelProviders/moonshot.ts, src/server/modules/AgentRuntime/index.ts
=> 🐛 fix: fix `MOONSHOT_PROXY_URL` behavior

src/services/chat.ts
=> 🐛 fix: fix `fetchOnClient` functional for Moonshot

src/server/modules/AgentRuntime/index.test.ts, src/server/modules/AgentRuntime/index.ts
=> 🐛 fix: fix fallback behavior of default mode in AgentRuntime

src/server/modules/AgentRuntime/index.test.ts, src/server/modules/AgentRuntime/index.ts
=> ♻️ refactor: optimize fallback behavior

.github/workflows/docker-database.yml, .github/workflows/docker.yml, Dockerfile, Dockerfile.database
=> 👷 build: optimize docker build speed via Github Actions

Dockerfile, Dockerfile.database
=> 👷 build: upgrade node to 22

Dockerfile, Dockerfile.database
=> 👷 build: upgrade nodejs version to 22

src/libs/agent-runtime/spark/index.ts, src/libs/agent-runtime/utils/streams/spark.ts
=> ♻️ refactor: add non-stream mode support

src/libs/agent-runtime/spark/index.ts
=> ⚡️ perf: using stream mode for tools call

Dockerfile, Dockerfile.database, src/libs/agent-runtime/antgroup/index.ts
=> 👷 build: add AntGroup ENV

src/libs/agent-runtime/spark/index.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
=> ✨ feat: add `handleStream` & `handleStreamResponse` for LobeOpenAICompatibleFactory, custom stream handle

src/libs/agent-runtime/spark/index.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
=> ✨ feat: add `handleTtransformResponseToStream` for custom non-stream transform handle

src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts
=> 🔨 chore: add unit test for LobeOpenAICompatibleFactory

src/libs/agent-runtime/utils/streams/spark.test.ts
=> 🔨 chore: add unit test for SparkAIStream

src/libs/agent-runtime/qwen/index.ts
=> 🐛 fix: fix Qwen param range error

src/libs/agent-runtime/qwen/index.ts
=> 🔨 chore: add `QwenLegacyModels` array, limit `presence_penalty`

src/libs/agent-runtime/spark/index.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.test.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
=> 🐛 fix: fix typo

src/app/(main)/chat/(workspace)/@topic/features/TopicListContent/TopicItem/index.tsx, src/app/(main)/chat/(workspace)/_layout/Mobile/TopicModal.tsx
=> 🐛 fix: fix topic mobile view ui error

src/libs/agent-runtime/qwen/index.ts
=> ♻️ refactor: intro `QwenEnableSearchModelSeries` to control `enable_search` parameter

src/libs/agent-runtime/qwen/index.ts
=> 🔨 chore: add env to control `enable_search` & `search_strategy`

src/config/modelProviders/mistral.ts, src/libs/agent-runtime/mistral/index.ts
=> 💄 style: add Mistral ModelFetcher support

src/config/modelProviders/minimax.ts
=> 💄 style: add vision tag for `abab6.5s-chat` & `abab7-chat-preview`

src/config/aiModels/ai360.ts, src/config/aiModels/giteeai.ts, src/config/aiModels/taichu.ts, src/config/aiModels/upstage.ts, src/config/aiModels/zhipu.ts
=> 💄 style: update aiModels list

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/fireworksai/index.ts, src/libs/agent-runtime/giteeai/index.ts, src/libs/agent-runtime/groq/index.ts, src/libs/agent-runtime/internlm/index.ts, src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/qwen/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/siliconcloud/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/xai/index.ts, src/libs/agent-runtime/zeroone/index.ts
=> ♻️ refactor: use aiModels sheme

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/fireworksai/index.ts, src/libs/agent-runtime/giteeai/index.ts, src/libs/agent-runtime/groq/index.ts, src/libs/agent-runtime/internlm/index.ts, src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/qwen/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/siliconcloud/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/xai/index.ts, src/libs/agent-runtime/zeroone/index.ts
Reverts hezhijie0327/lobe-chat#251
=> Revert "♻️ refactor: use aiModels sheme"

src/libs/agent-runtime/fireworksai/index.ts
=> 🐛 fix: fix `firefunction` series not set as functionCall

src/config/modelProviders/zhipu.ts, src/libs/agent-runtime/zhipu/index.ts
=> 💄 style: add Zhipu FetchModel support

src/config/modelProviders/anthropic.ts, src/libs/agent-runtime/anthropic/index.ts
=> 💄 style: add Anthropic FetchModel support

src/config/modelProviders/google.ts, src/libs/agent-runtime/anthropic/index.ts, src/libs/agent-runtime/google/index.ts
=> 💄 style: add Google ModelFetch support

src/config/modelProviders/huggingface.ts, src/libs/agent-runtime/huggingface/index.ts
=> 💄 style: add HuggingFace ModelFetch support

src/config/aiModels/minimax.ts, src/config/modelProviders/minimax.ts
=> 💄 style: add releaseAt tag

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/anthropic/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/fireworksai/index.ts, src/libs/agent-runtime/giteeai/index.ts, src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/google/index.ts, src/libs/agent-runtime/groq/index.ts, src/libs/agent-runtime/higress/index.ts, src/libs/agent-runtime/huggingface/index.ts, src/libs/agent-runtime/internlm/index.ts, src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/openrouter/index.ts, src/libs/agent-runtime/qwen/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/siliconcloud/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/togetherai/index.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts, src/libs/agent-runtime/xai/index.ts, src/libs/agent-runtime/zeroone/index.ts, src/libs/agent-runtime/zhipu/index.ts
=> ♻️ refactor: refactor `LOBE_DEFAULT_MODEL_LIST` import

src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/higress/index.ts, src/libs/agent-runtime/openrouter/index.ts, src/libs/agent-runtime/togetherai/index.ts, src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts
=> 🔨 chore: revert some changes

src/config/aiModels/moonshot.ts, src/libs/agent-runtime/moonshot/index.ts
=> 💄 style: add vision model support for Moonshot

src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/qwen/index.ts, src/libs/agent-runtime/stepfun/index.ts
=> 💄 style: add model fetch support for Hunyuan & fix some model fetch error

src/config/aiModels/hunyuan.ts, src/libs/agent-runtime/hunyuan/index.ts
=> 🐛 fix: fix Hunyuan model fetch ci error

src/libs/agent-runtime/hunyuan/index.ts
=> 💄 style: remove fc tag for Hunyuan vision model

src/config/modelProviders/ollama.ts
=> 🐛 fix: fix ollama Browser Request failed in PG mode

src/config/aiModels/github.ts, src/config/aiModels/openai.ts, src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/openai/index.ts
=> 💄 style: add `o3-mini` support for OpenAI & GitHub Models

src/libs/agent-runtime/openai/index.ts
=> 🔨 chore: change `system` role to `developer` for reasoning model

src/app/(main)/discover/(detail)/model/[...slugs]/features/ParameterList/index.tsx
=> 💄 style: add `reasoning_effort` intro to discover page

Dockerfile, Dockerfile.database
=> 🐛 fix: fix pnpm cannot be installed via corepack due to key id mismatch

Dockerfile, Dockerfile.database
=> 🔨 chore: workaround need update corepack to latest

Dockerfile, Dockerfile.database
=> 🔨 chore: drop `jq` deps, use `sed` instead

src/config/aiModels/fireworksai.ts, src/config/modelProviders/fireworksai.ts
=> 💄 style: update Fireworks AI model list

src/app/(main)/settings/provider/features/ModelList/CreateNewModelModal/Form.tsx, src/locales/default/modelProvider.ts, src/utils/_deprecated/parseModels.ts, src/utils/parseModels.test.ts, src/utils/parseModels.ts
=> 💄 style: add custom reasoning tag support

src/config/aiModels/giteeai.ts, src/config/aiModels/huggingface.ts, src/config/aiModels/perplexity.ts
=> 💄 style: add missing reasoning tag

src/config/aiModels/giteeai.ts, src/config/aiModels/huggingface.ts, src/config/aiModels/perplexity.ts
Reverts hezhijie0327/lobe-chat#288
=> Revert "💄 style: add missing reasoning tag"

src/config/aiModels/internlm.ts
=> 💄 style: add `internlm3-latest` for InternLM

src/hooks/useModelSupportReasoning.ts, src/store/aiInfra/slices/aiModel/action.ts, src/store/aiInfra/slices/aiModel/selectors.ts, src/store/user/slices/modelList/selectors/modelProvider.ts, src/types/llm.ts, src/utils/_deprecated/parseModels.ts
=> 🔨 chore: sync code

src/types/aiModel.ts
=> 🔨 chore: add missing type

src/utils/_deprecated/parseModels.test.ts
=> 🔨 chore: add test unit

src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/openai/index.ts
=> 🐛 fix: fix `o1` series calling issue

docs/usage/providers/wenxin.mdx, docs/usage/providers/wenxin.zh-CN.mdx
=> 📝 docs: update docs

src/libs/agent-runtime/siliconcloud/index.ts
=> 🐛 fix: fix `deepseek-v3` & `qvq` model tag fetch error from SiliconCloud

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/anthropic/index.ts, src/libs/agent-runtime/cloudflare/index.ts, src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/fireworksai/index.ts, src/libs/agent-runtime/giteeai/index.ts, src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/google/index.ts, src/libs/agent-runtime/groq/index.ts, src/libs/agent-runtime/higress/index.ts, src/libs/agent-runtime/huggingface/index.ts, src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/internlm/index.ts, src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/novita/index.ts, src/libs/agent-runtime/openrouter/index.ts, src/libs/agent-runtime/qwen/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/siliconcloud/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/togetherai/index.ts, src/libs/agent-runtime/xai/index.ts, src/libs/agent-runtime/zeroone/index.ts, src/libs/agent-runtime/zhipu/index.ts
=> ♻️ refactor: refactor model fetch method

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/anthropic/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/cloudflare/index.ts, src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/fireworksai/index.ts, src/libs/agent-runtime/giteeai/index.ts, src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/google/index.ts, src/libs/agent-runtime/groq/index.ts, src/libs/agent-runtime/higress/index.ts, src/libs/agent-runtime/huggingface/index.ts, src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/internlm/index.ts, src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/novita/index.ts, src/libs/agent-runtime/ollama/index.test.ts, src/libs/agent-runtime/ollama/index.ts, src/libs/agent-runtime/openrouter/__snapshots__/index.test.ts.snap, src/libs/agent-runtime/openrouter/index.ts, src/libs/agent-runtime/qwen/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/siliconcloud/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/togetherai/__snapshots__/index.test.ts.snap, src/libs/agent-runtime/togetherai/index.ts, src/libs/agent-runtime/xai/index.ts, src/libs/agent-runtime/zeroone/index.ts, src/libs/agent-runtime/zhipu/index.ts
=> 🐛 fix: fix model name matching error

src/app/(backend)/webapi/chat/models/[provider]/route.ts
=> 🐛 fix: fix togetherai apiKey missing when fetch model list

src/libs/agent-runtime/cloudflare/index.ts, src/libs/agent-runtime/utils/cloudflareHelpers.test.ts, src/libs/agent-runtime/utils/cloudflareHelpers.ts
=> 🔨 chore: cleanup unused code

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/anthropic/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/cloudflare/index.ts, src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/fireworksai/index.ts, src/libs/agent-runtime/giteeai/index.ts, src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/google/index.ts, src/libs/agent-runtime/groq/index.ts, src/libs/agent-runtime/higress/index.ts, src/libs/agent-runtime/huggingface/index.ts, src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/internlm/index.ts, src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/novita/index.ts, src/libs/agent-runtime/openai/index.ts, src/libs/agent-runtime/openrouter/index.ts, src/libs/agent-runtime/qwen/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/siliconcloud/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/togetherai/index.ts, src/libs/agent-runtime/xai/index.ts, src/libs/agent-runtime/zeroone/index.ts, src/libs/agent-runtime/zhipu/index.ts
=> ♻️ refactor: refactor model fetch behavior

src/libs/agent-runtime/anthropic/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/cloudflare/index.ts, src/libs/agent-runtime/github/index.ts, src/libs/agent-runtime/google/index.ts, src/libs/agent-runtime/huggingface/index.ts, src/libs/agent-runtime/ollama/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/togetherai/index.ts, src/libs/agent-runtime/zhipu/index.ts
=> ♻️ refactor: refactor import `LOBE_DEFAULT_MODEL_LIST` with async method - Part 1

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/anthropic/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/deepseek/index.ts, src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/internlm/index.ts, src/libs/agent-runtime/mistral/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/tencentcloud/index.ts, src/libs/agent-runtime/xai/index.ts, src/libs/agent-runtime/zeroone/index.ts
=> 🔨 chore: add vision, reasoning, fc default value

Dockerfile, Dockerfile.database, src/config/modelProviders/jina.ts
=> 💄 style: add `proxyUrl` support

src/config/aiModels/sambanova.ts, src/config/modelProviders/sambanova.ts
=> 🔨 chore: disable Browser Request & `DeepSeek-R1` model

src/config/aiModels/jina.ts, src/config/modelProviders/jina.ts
=> 💄 style: update Jina AI Provider name & model info

src/config/aiModels/moonshot.ts, src/libs/agent-runtime/moonshot/index.ts
=> 💄 style: add `kimi-latest` for Moonshot

src/config/aiModels/ai360.ts, src/config/aiModels/baichuan.ts, src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/baichuan/index.ts
=> ✨ feat: add online search support for available providers

src/config/aiModels/hunyuan.ts, src/config/aiModels/minimax.ts, src/config/aiModels/moonshot.ts, src/config/aiModels/stepfun.ts, src/config/aiModels/zhipu.ts, src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/minimax/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/zhipu/index.ts
=> ✨ feat: add more providers support

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/stepfun/index.ts
=> 🐛 fix: fix stream for fc

src/libs/agent-runtime/ai360/index.ts, src/libs/agent-runtime/baichuan/index.ts, src/libs/agent-runtime/minimax/index.ts, src/libs/agent-runtime/moonshot/index.ts, src/libs/agent-runtime/stepfun/index.ts, src/libs/agent-runtime/zhipu/index.ts
=> ♻️ refactor: refactor tools

src/config/aiModels/wenxin.ts, src/libs/agent-runtime/wenxin/index.ts
=> ✨ feat: add build-in web search support for Wenxin

src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/utils/streams/openai.ts, src/libs/agent-runtime/utils/streams/protocol.ts, src/libs/agent-runtime/wenxin/index.ts
=> ✨ feat: add support wenxin & hunyuan search_info stream

src/libs/agent-runtime/hunyuan/index.ts, src/libs/agent-runtime/utils/streams/openai.ts, src/libs/agent-runtime/utils/streams/protocol.ts
=> ✨ feat: add `search_info` stream support for Hunyuan

src/libs/agent-runtime/utils/streams/openai.ts
=> 🔨 chore: minor logic

src/libs/agent-runtime/hunyuan/index.test.ts, src/libs/agent-runtime/wenxin/index.test.ts
=> 🐛 fix: try to fix ci error

src/server/modules/SearXNG.ts, src/server/routers/tools/search.ts, src/services/search.ts, src/store/chat/slices/builtinTool/actions/searXNG.ts, src/tools/web-browsing/index.ts, src/tools/web-browsing/systemRole.ts, src/types/tool/search.ts
=> ✨ feat: add categories & time_range support for SearXNG

src/tools/web-browsing/index.ts, src/tools/web-browsing/systemRole.ts
=> 🐛 fix: fix week option missing

src/tools/web-browsing/components/SearchBar.tsx
=> 🐛 fix: fix time_range intro

src/tools/web-browsing/components/SearchBar.tsx
=> 🐛 fix: try to fix selection with anytime of time_range 

src/server/modules/SearXNG.ts, src/tools/web-browsing/components/SearchBar.tsx, src/tools/web-browsing/index.ts, src/tools/web-browsing/systemRole.ts
=> 🐛 fix: fix anytime option behavior

src/server/modules/SearXNG.ts, src/tools/web-browsing/systemRole.ts
=> ♻️ refactor: improve system prompt

src/store/chat/slices/builtinTool/actions/searXNG.test.ts, src/store/chat/slices/builtinTool/actions/searXNG.ts, src/tools/web-browsing/index.ts, src/tools/web-browsing/systemRole.ts, src/types/tool/search.ts
=> 🔨 chore: cleanup code

src/config/aiModels/cohere.ts, src/config/modelProviders/cohere.ts, src/libs/agent-runtime/cohere/index.ts
=> 💄 style: update cohere model list

src/libs/agent-runtime/cohere/index.ts
=> 🐛 fix: fix cohere calling, exclude user and stream_options

src/libs/agent-runtime/cohere/index.ts
=> 🐛 fix: fix cohere model list fetch

src/store/chat/slices/builtinTool/actions/searXNG.test.ts, src/store/chat/slices/builtinTool/actions/searXNG.ts
=> ♻️ refactor: refactor search retry logic

src/tools/web-browsing/components/SearchBar.tsx, src/tools/web-browsing/const.ts, src/tools/web-browsing/systemRole.ts
=> 🐛 fix: fix build error

src/tools/web-browsing/components/CategoryAvatar.tsx, src/tools/web-browsing/components/SearchBar.tsx, src/tools/web-browsing/systemRole.ts
=> 💄 style: optimize CategoryAvatar display

src/tools/web-browsing/components/CategoryAvatar.tsx
=> 💄 style: update CategoryAvatar style

src/tools/web-browsing/index.ts, src/tools/web-browsing/systemRole.ts
=> 🔨 chore: update system prompt

src/store/chat/slices/builtinTool/actions/searXNG.test.ts, src/store/chat/slices/builtinTool/actions/searXNG.ts, src/types/tool/search.ts
=> 🔨 chore: add `img_src` to SearchContent

src/store/chat/slices/builtinTool/actions/searXNG.test.ts, src/store/chat/slices/builtinTool/actions/searXNG.ts, src/types/tool/search.ts
=> 🔨 chore: support more details info, `publishedDate`, `thumbnail`

src/config/modelProviders/xinference.ts, src/libs/agent-runtime/xinference/index.ts
=> 🐛 fix: fix model list fetch data miss match

locales/zh-CN/tool.json, src/locales/default/tool.ts, src/tools/web-browsing/Render/Search/SearchQuery/SearchView.tsx, src/tools/web-browsing/components/SearchBar.tsx
=> 💄 style: improve mobile view, if engines is empty

src/libs/agent-runtime/xai/index.ts
=> 🐛 fix: fix `grok-3-mini` series calling

src/config/aiModels/ai360.ts, src/config/aiModels/stepfun.ts, src/config/aiModels/taichu.ts, src/config/aiModels/volcengine.ts
=> 💄 style: update 360 AI & Taichu model list

src/config/aiModels/github.ts, src/config/aiModels/taichu.ts
=> 💄 style: update Github Models list

src/libs/agent-runtime/sensenova/index.ts
=> 🐛 fix: fix `SenseNova-V6` series calling

src/libs/agent-runtime/sensenova/index.ts, src/libs/agent-runtime/utils/sensenovaHelpers.ts
=> ♻️ refactor: move SenseNova V6 logic to `convertSenseNovaMessage`

src/config/aiModels/volcengine.ts
=> 💄 style: fix `doubao-1-5-thinking-pro-vision` endpoint calling

src/libs/agent-runtime/utils/streams/spark.ts
=> 🔨 chore: support `reasoning_content` & `usage` for Spark

src/libs/agent-runtime/utils/streams/spark.ts
=> 🔨 chore: support Spark `v1` usage

src/tools/web-browsing/index.ts, src/tools/web-browsing/systemRole.ts
=> ♻️ refactor: improve categories selection via SearXNG

src/config/aiModels/xai.ts, src/libs/model-runtime/xai/index.ts
=> 💄 style: remove `grok-3-mini` search tag

src/config/aiModels/xai.ts, src/libs/model-runtime/xai/index.ts
=> 🐛 fix: fix `grok-3-mini` live search calling

src/libs/model-runtime/anthropic/index.ts
=> 💄 style: support beta headers

src/libs/model-runtime/utils/streams/anthropic.ts
=> ♻️ refactor: support citations from web_search_tools

src/libs/model-runtime/utils/streams/openai.ts, src/libs/model-runtime/zhipu/index.ts
=> ♻️ refactor: refactor zhipu `web_search` tools

src/libs/model-runtime/utils/streams/anthropic.ts, src/libs/model-runtime/utils/streams/protocol.ts
=> ♻️ refactor: better citations handling

packages/web-crawler/src/crawImpl/index.ts, packages/web-crawler/src/crawImpl/tavily.ts
=> ✨ feat: support tavily as crawl provider

src/server/services/search/impls/firecrawl/index.ts, src/server/services/search/impls/firecrawl/type.ts, src/server/services/search/impls/index.ts
=> ✨ feat: support firecrawl as search provider

packages/web-crawler/src/crawImpl/firecrawl.ts, src/server/services/search/impls/firecrawl/index.ts
=> 🔨 chore: support firecrawl baseUrl for self-host

src/server/services/search/impls/index.ts, src/server/services/search/impls/jina/index.ts, src/server/services/search/impls/jina/type.ts
=> ✨ feat: support jina as search provider

src/server/services/search/impls/bocha/index.ts, src/server/services/search/impls/bocha/type.ts, src/server/services/search/impls/index.ts
=> 🔨 chore: rename to bocha

src/server/services/search/impls/bocha/index.ts, src/server/services/search/impls/bocha/type.ts
=> 🐛 fix: fix typo in Bocha impl

src/server/services/search/impls/exa/index.ts
=> ♻️ refactor: add time_range support for Exa

src/server/services/search/impls/exa/index.ts
=> ♻️ refactor: add category support for exa

src/libs/model-runtime/utils/openaiHelpers.ts
=> ✨ feat: support template variables in prompt

src/services/chat.ts, src/utils/parserPlaceholder.ts
=> ♻️ refactor: migrate to `lodash-es`

src/services/chat.ts, src/utils/parserPlaceholder.ts
=> ♻️ refactor: split `getTemplateVariables` to small part

src/utils/parserPlaceholder.ts
=> ♻️ refactor: enhance performance

src/store/user/slices/auth/selectors.ts
=> 🐛 fix: fix `username` fetch

src/libs/model-runtime/perplexity/index.test.ts, src/libs/model-runtime/utils/streams/ollama.test.ts, src/libs/model-runtime/utils/streams/ollama.ts, src/libs/model-runtime/utils/streams/openai.test.ts
=> 🔨 chore: add unit test & support ollama stream

src/libs/model-runtime/utils/streams/ollama.ts, src/libs/model-runtime/utils/streams/openai.ts
=> ♻️ refactor: improve `<think>` regex

src/config/aiModels/openai.ts, src/libs/model-runtime/utils/openaiCompatibleFactory/index.ts
=> 🐛 fix: fix `reasoning_effort` error in response api

src/libs/model-runtime/types/chat.ts, src/libs/model-runtime/utils/openaiCompatibleFactory/index.ts, src/libs/model-runtime/utils/streams/openai/__snapshots__/responsesStream.test.ts.snap
=> 🐛 fix: fix ci test

src/config/aiModels/openai.ts, src/const/models.ts, src/libs/model-runtime/openai/index.ts
=> ♻️ refactor: add `responsesAPIModels` to store responses api only

src/server/services/search/impls/brave/index.ts, src/server/services/search/impls/brave/type.ts, src/server/services/search/impls/index.ts
=> ✨ feat: add Brave Search as build-in Search Provider

src/server/services/search/impls/index.ts, src/server/services/search/impls/kagi/index.ts, src/server/services/search/impls/kagi/type.ts
=> ✨ feat: add Kagi as build-in Search Provider

src/server/services/search/impls/google/index.ts, src/server/services/search/impls/google/type.ts, src/server/services/search/impls/index.ts
=> ✨ feat: add Google PSE as build-in Search Provider

src/server/services/search/impls/anspire/index.ts, src/server/services/search/impls/anspire/type.ts, src/server/services/search/impls/index.ts
=> ✨ feat: add Anspire (安思派) as build-in Search Provider

docs/self-hosting/advanced/online-search.zh-CN.mdx
=> 📝 docs: add docs

docs/self-hosting/advanced/online-search.zh-CN.mdx
=> 📝 docs: improve doc

Dockerfile, Dockerfile.database, Dockerfile.pglite
=> 🔨 chore: update Dockerfile ENV

src/config/aiModels/v0.ts, src/libs/model-runtime/utils/modelParse.ts
=> 💄 style: fix reasoning tag

src/libs/model-runtime/openai/index.ts
=> 🐛 fix: reasoning model calling

src/config/aiModels/siliconcloud.ts, src/config/aiModels/stepfun.ts, src/config/aiModels/wenxin.ts, src/config/aiModels/xai.ts
=>  💄 style: add more OpenAI Mode Text2Image providers

src/config/aiModels/siliconcloud.ts, src/config/aiModels/stepfun.ts, src/config/aiModels/wenxin.ts, src/config/aiModels/xai.ts
=> 🔨 chore: update desc & release date

src/config/aiModels/giteeai.ts, src/config/aiModels/stepfun.ts, src/config/aiModels/wenxin.ts
=> 💄 style: support image edit models

src/config/aiModels/qwen.ts, src/libs/model-runtime/qwen/createImage.ts
=> 💄 style: support more Text2Image from Qwen

src/config/aiModels/qwen.ts, src/libs/model-runtime/qwen/createImage.ts
=> 🐛 fix: try to fix size

src/config/aiModels/minimax.ts, src/libs/model-runtime/minimax/createImage.ts, src/libs/model-runtime/minimax/index.ts
=> 💄 style: support Minimax T2I models

src/config/aiModels/qwen.ts, src/libs/model-runtime/qwen/createImage.ts
=> 🔨 chore: apply suggestion

src/libs/model-runtime/minimax/createImage.test.ts, src/libs/model-runtime/minimax/createImage.ts
=> 🔨 chore: add unit test & baseUrl support for Global endpoint
